    <footer  class=" text-center mt-5" style="margin-top:200px">
        <nav class="navbar navbar-expand-lg navbar-light bg-light ">

              <div class="container-fluid text-center ">

                
                <a class="navbar-brand text-black" href="#">BADNeWS <img src="assets/images/attaque.png" alt="" width="30"></a>
                
                <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" 
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button> -->
                
                    <div class="collapse navbar-collapse text-center" id="navbarNavDropdown" style="margin-left:30%">
                        <ul class="navbar-nav text-center ml-5" >

                          <li class="nav-item ">
                            <a class="nav-link active text-black" aria-current="page" href="https://www.instagram.com/?hl=fr"><img src="assets/images/insta.png" alt="" width="50"  ></a>
                          </li>

                          <li class="nav-item">
                            <a class="nav-link text-black" href="https://fr-fr.facebook.com/"><img src="assets/images/face.png" alt="" width="50" style="margin-left:30%"></a>
                          </li>

                          <li class="nav-item">
                            <a class="nav-link text-black" href="https://twitter.com/?lang=fr"><img src="assets/images/tik.png" alt="" width="50" style="margin-left:50%"></a>
                          </li>

                        </ul>
                  </div>


                    <div class="text-right text-danger col-4"> Copyright &copy;<a class="text-danger" href="admin/index.php" style="text-decoration:none">2021</a></div>
              </div>
        </nav>
    </footer>
  </body>
</html>